import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const schema = defineSchema({
  waitlist: defineTable({
    email: v.string(),
    position: v.number(),
    joinedAt: v.number(),
    referral: v.optional(v.string()),
  }).index("by_email", ["email"]),

  /** Person contacts attached to a Places result; synced to Lead Flow. */
  placeContacts: defineTable({
    placeId: v.string(),
    placeName: v.string(),
    formattedAddress: v.optional(v.string()),
    name: v.string(),
    email: v.string(),
    role: v.optional(v.string()),
    phone: v.optional(v.string()),
    notes: v.optional(v.string()),
    leadFlowLeadId: v.optional(v.string()),
    syncStatus: v.union(v.literal("pending"), v.literal("synced"), v.literal("failed")),
    syncError: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_placeId", ["placeId"]),

  /** User-pinned places for `/pinned` filter (one row per placeId). */
  placePins: defineTable({
    placeId: v.string(),
    placeName: v.string(),
    formattedAddress: v.optional(v.string()),
    lat: v.optional(v.number()),
    lng: v.optional(v.number()),
    pinnedAt: v.number(),
  }).index("by_placeId", ["placeId"]),

  /**
   * Cached place entities from SerpAPI (predictions + optional details).
   * Used so `/places` can load from Convex before hitting SerpAPI again.
   */
  places: defineTable({
    placeId: v.string(),
    mainText: v.string(),
    secondaryText: v.optional(v.string()),
    lat: v.optional(v.number()),
    lng: v.optional(v.number()),
    rating: v.optional(v.number()),
    reviewCount: v.optional(v.number()),
    openState: v.optional(v.string()),
    thumbnail: v.optional(v.string()),
    formattedAddress: v.optional(v.string()),
    types: v.optional(v.array(v.string())),
    mapsUri: v.optional(v.string()),
    website: v.optional(v.string()),
    phone: v.optional(v.string()),
    reviews: v.optional(
      v.array(
        v.object({
          author: v.optional(v.string()),
          rating: v.optional(v.number()),
          text: v.string(),
          date: v.optional(v.string()),
        }),
      ),
    ),
    images: v.optional(v.array(v.string())),
    hours: v.optional(
      v.array(
        v.object({
          day: v.string(),
          hours: v.string(),
        }),
      ),
    ),
    hasDetails: v.boolean(),
    provider: v.literal("serpapi"),
    fetchedAt: v.number(),
    detailsFetchedAt: v.optional(v.number()),
  }).index("by_placeId", ["placeId"]),

  /** Cached SerpAPI autocomplete pages keyed by normalized query + bias + start. */
  placeSearches: defineTable({
    queryKey: v.string(),
    query: v.string(),
    lat: v.optional(v.number()),
    lng: v.optional(v.number()),
    start: v.number(),
    placeIds: v.array(v.string()),
    nextStart: v.optional(v.number()),
    fetchedAt: v.number(),
    provider: v.literal("serpapi"),
  }).index("by_queryKey", ["queryKey"]),

  /** Learning packs generated by signed-in Google users on /youtube. */
  youtubeLearningPacks: defineTable({
    googleSub: v.string(),
    email: v.optional(v.string()),
    videoId: v.string(),
    videoTitle: v.string(),
    channelTitle: v.optional(v.string()),
    /** Pack content type / topic kind (tutorial, lecture, talk, …). Optional on older rows. */
    contentType: v.optional(v.string()),
    markdown: v.string(),
    /** Source transcript used to generate the pack (optional on older rows). */
    transcript: v.optional(v.string()),
    /**
     * Snapshot of the knowledge graph (nodes + links) for instant reload.
     * Optional on older rows — Graph tab rebuilds from markdown when missing.
     */
    graphPayload: v.optional(
      v.object({
        nodes: v.array(v.any()),
        links: v.array(v.any()),
      }),
    ),
    createdAt: v.number(),
  }).index("by_googleSub_createdAt", ["googleSub", "createdAt"]),

  /**
   * Transcript summaries (VN/EN) for signed-in users on /youtube.
   * One row per user + video; language fields are patched independently.
   */
  youtubeTranscriptSummaries: defineTable({
    googleSub: v.string(),
    email: v.optional(v.string()),
    videoId: v.string(),
    videoTitle: v.string(),
    channelTitle: v.optional(v.string()),
    summaryVi: v.optional(v.string()),
    summaryEn: v.optional(v.string()),
    /** Transcript used for the latest summary write (optional). */
    transcript: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_googleSub_videoId", ["googleSub", "videoId"]),

  /** Per-article knowledge graph snapshots for signed-in Google users on /news. */
  newsKnowledgeArticles: defineTable({
    googleSub: v.string(),
    email: v.optional(v.string()),
    storyId: v.string(),
    title: v.string(),
    canonicalUrl: v.string(),
    deepDiveText: v.optional(v.string()),
    graphPayload: v.object({
      nodes: v.array(v.any()),
      links: v.array(v.any()),
    }),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_googleSub_updatedAt", ["googleSub", "updatedAt"])
    .index("by_googleSub_storyId", ["googleSub", "storyId"]),

  /** User-created cross-entity links in the personal news knowledge graph. */
  newsKnowledgeLinks: defineTable({
    googleSub: v.string(),
    sourceNodeKey: v.string(),
    targetNodeKey: v.string(),
    type: v.union(
      v.literal("RELATED_TO"),
      v.literal("SUPPORTS"),
      v.literal("CONTRASTS_WITH"),
    ),
    note: v.optional(v.string()),
    createdAt: v.number(),
  })
    .index("by_googleSub_createdAt", ["googleSub", "createdAt"])
    .index("by_googleSub_endpoints", [
      "googleSub",
      "sourceNodeKey",
      "targetNodeKey",
      "type",
    ]),

  /**
   * Favorite language/topic chips for /github monitor (one row per Google user).
   * Topics are catalog ids (typescript, ai, rust, …).
   */
  githubFavorites: defineTable({
    googleSub: v.string(),
    email: v.optional(v.string()),
    topics: v.array(v.string()),
    updatedAt: v.number(),
  }).index("by_googleSub", ["googleSub"]),
});

export default schema;
